// Builds the DRIFT_BINDINGS data block that setup-shortcuts.sh sources, from
// SETTINGS_DEFINITIONS. Pure and side-effect-free so it's directly unit-testable;
// generate-shortcut-bindings.ts is the thin script wrapper that prints this to stdout
// for the build.

import type { SettingsDefinition, ShortcutMetadata } from './settings-definitions';

type ShortcutSettingsDefinition = SettingsDefinition & { shortcut: ShortcutMetadata };

function hasShortcutMetadata(def: SettingsDefinition): def is ShortcutSettingsDefinition {
    return def.shortcut !== undefined;
}

/** "shortcutFocusLeft" -> "DriftFocusLeft" — the naming convention linking a settings key
 * to its kglobalaccel action name. */
export function driftActionNameFor(settingsKey: string): string {
    return `Drift${settingsKey.replace(/^shortcut/, '')}`;
}

export function buildShortcutBindingsScript(definitions: SettingsDefinition[]): string {
    const rows = definitions
        .filter(hasShortcutMetadata)
        .map((def) => {
            const actionName = driftActionNameFor(def.name);
            const actionText = `Drift: ${def.shortcut.label}`;
            const sequence = def.default as string;
            const altSequence = def.shortcut.altDefault;
            return altSequence
                ? `${actionName}|${actionText}|${sequence}|${altSequence}`
                : `${actionName}|${actionText}|${sequence}`;
        })
        .join('\n');
    return (
        '# Generated by generate-shortcut-bindings.ts from src/config/settings-definitions.ts — do not edit by hand.\n' +
        '# Sourced by setup-shortcuts.sh. Columns: action_name|action_text|sequence|alt_sequence (alt optional).\n' +
        "DRIFT_BINDINGS='\n" +
        rows +
        "\n'\n"
    );
}
